#!/bin/bash

#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe mpi_16_tasks_per_node 16

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"

# your commands here
tophat -r 200 -G /projectnb/bf528/project_2/reference/annot/mm9.gtf --segment-length=20 --segment-mismatches=1 --no-novel-juncs -o P0_1_tophat -p 16 /projectnb/bf528/project_2/reference/mm9 fastq/P0_1_1.fastq fastq/P0_1_2.fastq 

echo "Job finished: $(date +%F)"
